var GAME_LEVELS = [
//recreating first level with real floaters and not coin-wannabes
//"y"=floater "x"=wall "@"=Player "!"=lava "o"=coin
["                                                                                  ",
"    y                                                                             ",
"   yyy              yy                              yy                            ",
"                  yyyy                            yyyyy                            ",
"                                                                                   ",
"  @                         o       xxxxxx                                         ",
"xxxxx                  o xxxxx                                                    ",
"    x                xxxxx   x             !!                                     ",
"    x    o          xxx      x             xx                                     ",//5
"    xxxxxxx     xxxxxx       x!!!!                 !!!          yy                ",
"          x!!!!!x            xxxx!!!!!!!!   !      xxx         yyyy                ",
"          x!!!!!x            xxxxxxxxxx!!   x                                     ",
"          xxxxxxx            xxxxxxxxxx!!!                                          ",
"                                      xxxx                                        ",//10
"                          y                       !!!                             ",
"                         yyy                   o  xxx                             ",
"                       yyyyyy                                                     ",
"                                             !!             !!                    ",
"                                             xx             xx                    ",
"                                                                                  ",//15
"                                                                                    ",
"                                                      o                           ",
"                                            xxxxxx   xxxxxxxx                      ",
"                                                          xxxxx    o   o      o    ",
"                                                                  xx  xxx    xxxxx",
"                                                                   x!!xxx!!!!xxxxx",
"x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx"], 
 

 //new level 2
["                                                                                   ",
"            xx                                                                     ",
"             xx                                                                    ",
"  @          xx                              xxx                                   ",
"    xxx      xx                              x!x                                   ",
"  o xxxxxx o xx        y                     x!x                                   ",
"xxxxxxxxxx   xx       yyy                    xvx                                   ",
"       xxx o xx                                                                    ",
"       xxx   xx                                           yyy                      ",
"       xxx   xx                                          yyyyy                     ",
"       xxx o xx                                                                    ",
"       xxx   xx                                                                    ",
"xxxxxxxxxx o xx                                 xxxx                               ",
"x                      w                        xxxx                               ",
"x=         o          xxxx   o  o  o   xxxx     xxxx                               ",
"xxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxxx   xxxx                               ",
"                    xxxxxx!!!!!!!!!!!!!xxxx     xxxx                               ",
"                       xxxxxxxxxxxxxxxxxxxx     xxxx                               ",
"                                       xxxx   xxxxxx                               ",
"                                       xxxx     xxxx                               ",
"                                       xxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
"                                       xxxx                              xx        ",
"                                       xxxx                              xx        ",
"                                       xxxxxxxxxxxxxxxxxxx         ! x ! xx        ",
"                                                   xxxxxxxxxxxxxxxxxxxxxxxx        ",
"                                                                                   ",
"                                                                                   ",
"                                                                                   "],
//level 3 w is wing PowerUP = is bullet right, < is bullet left
["                                                                                     ",
"                                                                                     ",
"                                                                                     ",
"   @                                                                                 ",
"                                                                                     ",
"   o                                                                                 ",
"xxxxxx                                                                               ",
"xxxxxx                                                                               ",
"x  xxx                         xxxxxxxxxxxx        o                                 ",
"x o xx                        xxx=  o   o                                            ",
"x o  x                        xxx  xxxxxxx  xxxx      o                              ",
"x                                   o   o  <xxxx            w                        ",
"xxxxxxxxxx                     xxxxxxxxxxxxxxxxx           xxxx    xxxx              ",
"x     xxxx                     xx                          xxxx    xxxx              ",
"x     xxxxxxx               xxxxx                          xxxx  o xxxx              ",
"x   o                xxxxxxxxxxxx                       xxxxxxx    xxxx              ",
"x   o       w   xxxxxxxxxxxx                            x=         xxxx              ",
"!!!!!!!!!xxxxxxxxxxxxxxxxxxx                            xxxxxxx    xxxxxxx           ",
"                                                           xxxx         <x           ",
"                                                           xxxx    xxxxxxx           ",
"                                                           xxxx  o xxxx              ",
"                                                        xxxxxxx    xxxx              ",
"                                                        x=         xxxx              ",
"                                                        xxxxxxx    xxxx              ",
"                                                           xxxx  o xxxx              ",
"                                                           xxxx    xxxx              ",
"                                                           xxxx    xxxx              ",
"                                                           xxxx  o xxxx              ",
"                                                           xxxx    xxxx              ",
"                                                                oo                   ",
"                                                     !!!!!!!!!!!xx!!!!!!!!!!!        ",
"                                                                                     ",
"                                                                                     ",
"                                                                                     ",
"                                                                                     ",
"                                                                                     "],



//Last Level, Win Screen
["                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"            xxxx  xxxx  xxxxx    xxxx       xxxx              yy                  ",
"              xx  xx   xx   xx     xx       xx              yyyyy     	           ",
"              xx  xx  xx     xx     xx     xx            yyyyyyyyyy               ",
"              xx  xx  xx     xx     xx     xx                                      ",
"                xx    xx     xx     xx     xx                                       ",
"                xx    xx     xx     xx     xx     yyyy                              ",
"                xx     xx   xx       xx   xx    yyyyyyy                             ",
"               xxxx     xxxxx         xxxxx                                         ",
"                                                                                  ",
"          xxxxx           xxxx xxxxxxx     xxxxx        xxxx                      ",
"            xxx    xx     xxx    xxx        xx xxx      xx                        ",
"             xx    xx     xx     xxx        xx  xx      xx                        ",
"             xx    xx     xx     xxx        xx   xx     xx                        ",
"             xx    xx     xx     xxx        xx    xx    xx                        ",
"     y       xx    xx     xx     xxx        xx     xx   xx                        ",
"    yyy       xx  xx xx  xx      xxx       xxxx      xx xx                        ",
"   yyyyy       xxxx   xxxx     xxxxxxx   xxxxx        xxxx                        ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  ",
"                                                                                  "]
];
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
